
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[290] =
    {   0,
        0,    0,   89,   87,    1,    2,   33,   87,   86,   53,
       51,   87,   72,   73,   48,   46,   74,   47,   76,   49,
       79,   79,   36,   77,   32,   30,   31,   35,   70,   71,
       52,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   68,   50,   69,   34,    1,
       41,    0,   85,    0,   86,   64,   45,   60,    0,    0,
       59,   42,   57,   43,   58,   37,   80,    0,   78,   63,
       80,   79,    0,    0,    0,   79,    0,    0,   79,   80,
        0,    0,   75,   55,   40,   38,    0,   39,   54,   62,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,

       86,   86,   16,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   61,   44,    0,
        0,   84,    0,    0,    0,   80,   80,    0,    0,    0,
        0,   78,   80,    0,   79,   79,    0,    0,   79,    0,
       80,    0,   79,   79,   79,    0,    0,   80,   79,   66,
        0,   65,   56,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   15,   86,   18,   86,   20,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
        0,    0,    0,    0,   80,    0,   78,   80,    0,    0,
       80,   79,   79,    0,   80,   80,    0,    0,    0,   79,

       79,    0,    0,   79,    0,   80,    0,   79,    0,    0,
       67,   86,   86,    6,    7,   86,   86,   86,   86,   12,
       86,   86,   86,   86,   19,   83,   86,   86,   86,   86,
       86,   86,   27,   81,   28,   86,   80,    0,    0,   80,
        0,    0,    0,    0,   80,    0,   86,    5,    8,    9,
       86,   86,   82,   13,   14,   86,   86,   86,   86,   86,
       25,   86,   29,   80,   80,    0,    0,   86,   86,   11,
       86,   86,   86,   23,   24,   26,    0,    4,   86,   86,
       21,   22,    0,   10,   86,    3,   86,   17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   29,   31,   32,   31,
        6,    6,    6,    6,    6,   33,    6,    6,    6,   34,
        6,    6,    6,    6,    6,    6,    6,   35,    6,    6,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,    6,   50,   51,    6,   52,
       53,   54,    6,   55,   56,   57,   58,   59,   60,   35,
       61,    6,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    6,
        6,    6,    1,    1,    1,    1,    1,    1,    6,    6,
        6,    6,    7,    8,    3,    1,    1,    1,    1,    8,
        6,    6,    6,    6,    6,    6,    3,    3,    3,    3,
        7,    3,    3,    8,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[301] =
    {   0,
        0,    0,  623,  782,  620,  782,  594,   61,    0,  593,
       59,  581,  782,  782,  590,   55,  782,   56,   54,   67,
       83,  119,  592,  782,   44,   51,   60,  782,  782,  782,
      588,   35,   58,  542,  543,   59,   43,  540,   33,   39,
      546,   69,   59,  537,  541,  782,   93,  782,  782,  586,
      782,  116,  782,  166,    0,  782,  782,  782,  577,  219,
      782,  782,  782,  782,  782,  782,  259,  573,    0,  782,
      288,  319,  160,  111,  175,  782,  568,  126,  195,  782,
      212,  223,  782,  556,  782,  782,  539,  782,  105,  782,
      527,  518,  505,  519,  517,  505,  498,  493,  494,  472,

      470,  465,    0,   86,  467,  458,  466,  455,  446,  452,
      429,  432,  420,  411,  401,  408,  407,  782,  782,  231,
      264,  782,  446,  239,  277,    0,  782,  303,  308,  442,
      110,    0,  353,  347,    0,  782,  336,  360,  368,  293,
      384,    0,  213,  370,    0,  413,  324,  418,  423,  782,
      395,  782,  424,  397,  406,  401,  374,  370,   98,  383,
      373,  361,  373,  372,    0,  355,    0,  360,    0,  345,
      342,  324,  326,  305,  306,  296,  294,  304,  303,  285,
      447,  131,  402,  451,  456,  145,  782,    0,  461,  470,
      485,  376,  782,  180,  490,  782,  519,  459,  115,  510,

      782,  533,  481,    0,  547,  552,  557,    0,  581,  274,
      782,  272,  252,    0,    0,  244,  237,  244,  241,    0,
      244,  237,  230,  234,    0,    0,  232,  231,  221,  211,
      205,  206,    0,    0,    0,  209,  586,  591,  155,  615,
      620,  488,  493,  629,  644,  171,  181,    0,    0,    0,
      167,  166,    0,    0,    0,  158,  162,  150,  163,  152,
        0,  159,    0,  649,  782,  678,  160,  139,  131,    0,
      140,  132,  129,    0,    0,    0,  130,    0,  116,  115,
        0,    0,  101,    0,   80,  782,   78,    0,  782,  718,
      724,  732,  740,  748,  752,  758,  114,  762,  770,  773

    } ;

static const flex_int16_t yy_def[301] =
    {   0,
      289,    1,  289,  289,  289,  289,  289,  290,  291,  289,
      289,  292,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  289,  289,  289,  289,  289,
      289,  290,  289,  289,  291,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  293,  294,  289,
      289,  289,  289,  289,  289,  289,  295,  289,   22,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  289,  289,  290,
      290,  289,  289,  289,  289,   67,  289,  289,  289,  293,
      296,  294,  289,  289,   72,  289,  289,  289,  289,  289,
      289,  297,  298,   72,   79,  289,  289,  289,   79,  289,
      289,  289,  289,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      290,  290,  289,  289,  289,  299,  289,  133,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  300,  297,  298,

      289,  289,  200,  144,  289,  289,  289,  149,  289,  289,
      289,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  289,  289,  299,  289,
      289,  300,  300,  289,  289,  289,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  289,  289,  289,  289,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  289,  291,  291,  291,
      291,  291,  289,  291,  291,  289,  291,  291,    0,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289

    } ;

static const flex_int16_t yy_nxt[848] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   23,   24,   25,   26,   27,   28,    9,    9,
        9,    9,    9,    9,    9,   29,    4,   30,   31,    9,
        9,   32,   33,   34,   35,   36,    9,    9,   37,    9,
       38,   39,    9,   40,   41,   42,   43,    9,   44,   45,
        9,   46,   47,   48,   49,   53,   57,   62,   84,   85,
       64,   67,   67,   67,   67,   67,   86,  106,   68,  108,
       63,   65,   66,   69,   58,   88,   89,   91,  103,   92,
      107,   87,   70,  109,  104,   93,  110,   54,   71,   99,

       72,   72,   72,   72,   73,   94,  114,  100,   95,  101,
       96,  102,   74,  115,   75,   76,  112,   77,  118,  198,
       53,  131,   78,  288,   74,  113,  187,   75,  139,  139,
      152,  153,  287,   76,   71,   53,   79,   79,   79,   79,
       79,  166,  167,  144,  144,  144,  144,   73,  202,   80,
       81,   76,   54,  217,  218,  119,  131,  286,   82,  285,
      284,  130,   80,   81,   80,   78,  131,   54,  202,   76,
       52,  130,  283,  282,   52,   71,  281,   73,   73,   73,
       73,   73,  280,  120,  120,  120,  121,  140,  279,  140,
      278,   75,  141,  141,  141,  141,  141,  192,  192,  138,

      277,  276,   52,  275,   75,  274,  273,   52,  272,  271,
      270,   52,  145,  145,  145,  145,  145,   52,  269,  194,
       52,  268,   52,  123,  147,  267,  147,  123,  199,  148,
      148,  148,  148,  148,  146,   53,  124,  124,  124,  125,
      149,  149,  149,  149,  149,  201,  202,  122,  181,  181,
      181,  181,  203,  263,  262,  123,  183,  183,  183,  183,
      123,  261,   82,  201,  123,  260,  202,   54,   53,  259,
      123,  258,  257,  123,  256,  123,  126,  126,  126,  126,
      126,  182,  182,  182,  182,  122,  255,  254,  253,  127,
      128,  252,  251,  250,  123,  123,  123,  123,  129,  249,

       54,  248,  127,  128,  127,  133,  133,  133,  133,  133,
      141,  141,  141,  141,  141,  184,  247,  184,   80,  134,
      185,  185,  185,  185,  185,  126,  126,  126,  126,  126,
      246,   80,  134,   80,   71,  236,  135,  135,  135,  135,
       73,  148,  148,  148,  148,  148,  235,  129,  234,  233,
       75,  136,  232,  135,  135,  135,  135,   73,  137,  190,
      231,  190,  230,   75,  191,  191,  191,  191,  191,  136,
      188,  188,  188,  188,  188,  137,  229,   73,   73,   73,
       73,   73,  228,   80,  134,  192,  192,  204,  204,  204,
      204,  227,  189,  192,  192,  226,   80,  134,   80,  138,

      193,  195,  195,  195,  195,  195,  225,  194,  193,  205,
      122,  224,  223,  222,  196,  194,  221,  220,  193,  123,
      123,  123,  123,  197,  219,  216,  193,  196,  215,  196,
      145,  145,  145,  145,  145,  206,  206,  206,  206,  206,
      208,  208,  208,  208,  208,  214,  213,  212,  196,  211,
      210,   53,  146,  131,  122,  180,  179,  207,  178,  177,
      176,  196,  209,  196,  182,  182,  182,  182,  185,  185,
      185,  185,  185,  237,  237,  237,  237,  237,  188,  188,
      188,  188,  188,   54,  175,  174,  127,  191,  191,  191,
      191,  191,  202,  173,  172,  238,  289,  171,  243,  127,

      189,  127,  240,  240,  240,  240,  240,  195,  195,  195,
      195,  195,  202,  289,  289,   80,  170,  169,  168,  165,
      196,  202,  164,  163,  241,  199,  289,  243,   80,  197,
       80,  289,  243,  196,  289,  196,  195,  195,  195,  195,
      195,  202,  201,  202,  162,  244,  289,  244,  161,  203,
      245,  245,  245,  245,  245,  160,  159,  158,  197,  157,
      201,  156,  155,  202,  204,  204,  204,  204,   73,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  154,
      151,  150,  196,  142,  131,  122,  205,   50,  117,  116,
      111,  207,  105,   98,   97,  196,  207,  196,  208,  208,

      208,  208,  208,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,   90,   83,   61,  127,   60,   56,   51,
      209,   50,  289,  289,  289,  238,  289,  289,  289,  127,
      238,  127,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  289,  289,  289,   80,  245,  245,  245,  245,
      245,  289,  289,  289,  241,  289,  289,  289,   80,  241,
       80,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  289,  289,  289,  265,  289,  289,  289,  289,  265,
      289,  289,  289,  266,  289,  289,  289,  265,  266,  265,
      289,  289,  265,  289,  265,  264,  264,  264,  264,  264,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  266,   52,  289,
       52,   52,   52,   52,   52,   52,   55,  289,  289,   55,
       55,   55,   59,  289,   59,  289,   59,   59,   59,   59,
      130,  130,  130,  130,  130,  130,  130,  130,  132,  289,
      132,  132,  132,  132,  132,  132,  143,  143,  186,  186,
      186,  186,  186,  186,  186,  186,  200,  200,  200,  200,
      239,  239,  239,  239,  239,  239,  239,  239,  242,  289,
      242,    3,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289
    } ;

static const flex_int16_t yy_chk[848] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,   11,   16,   25,   25,
       18,   19,   19,   19,   19,   19,   26,   39,   20,   40,
       16,   18,   18,   20,   11,   27,   27,   32,   37,   32,
       39,   26,   20,   40,   37,   32,   40,    8,   21,   36,

       21,   21,   21,   21,   21,   33,   43,   36,   33,   36,
       33,   36,   21,   43,   21,   21,   42,   21,   47,  297,
       52,  131,   21,  287,   21,   42,  131,   21,   74,   74,
       89,   89,  285,   21,   22,  182,   22,   22,   22,   22,
       22,  104,  104,   78,   78,   78,   78,   78,  199,   22,
       22,   22,   52,  159,  159,   47,  186,  283,   22,  280,
      279,  186,   22,   22,   22,   78,  239,  182,  199,   22,
       54,  239,  277,  273,   54,   73,  272,   73,   73,   73,
       73,   73,  271,   54,   54,   54,   54,   75,  269,   75,
      268,   73,   75,   75,   75,   75,   75,  194,  194,   73,

      267,  262,   54,  260,   73,  259,  258,   54,  257,  256,
      252,   54,   79,   79,   79,   79,   79,   54,  251,  194,
       54,  247,   54,   60,   81,  246,   81,   60,  143,   81,
       81,   81,   81,   81,   79,  120,   60,   60,   60,   60,
       82,   82,   82,   82,   82,  143,  143,  124,  120,  120,
      120,  120,  143,  236,  232,   60,  124,  124,  124,  124,
       60,  231,   82,  143,   60,  230,  143,  120,  121,  229,
       60,  228,  227,   60,  224,   60,   67,   67,   67,   67,
       67,  121,  121,  121,  121,  125,  223,  222,  221,   67,
       67,  219,  218,  217,  125,  125,  125,  125,   67,  216,

      121,  213,   67,   67,   67,   71,   71,   71,   71,   71,
      140,  140,  140,  140,  140,  128,  212,  128,   71,   71,
      128,  128,  128,  128,  128,  129,  129,  129,  129,  129,
      210,   71,   71,   71,   72,  180,   72,   72,   72,   72,
       72,  147,  147,  147,  147,  147,  179,  129,  178,  177,
       72,   72,  176,  137,  137,  137,  137,  137,   72,  134,
      175,  134,  174,   72,  134,  134,  134,  134,  134,   72,
      133,  133,  133,  133,  133,  137,  173,  138,  138,  138,
      138,  138,  172,  133,  133,  139,  139,  144,  144,  144,
      144,  171,  133,  192,  192,  170,  133,  133,  133,  138,

      139,  141,  141,  141,  141,  141,  168,  139,  192,  144,
      183,  166,  164,  163,  141,  192,  162,  161,  139,  183,
      183,  183,  183,  141,  160,  158,  192,  141,  157,  141,
      146,  146,  146,  146,  146,  148,  148,  148,  148,  148,
      149,  149,  149,  149,  149,  156,  155,  154,  148,  153,
      151,  181,  146,  130,  123,  117,  116,  148,  115,  114,
      113,  148,  149,  148,  181,  181,  181,  181,  184,  184,
      184,  184,  184,  185,  185,  185,  185,  185,  189,  189,
      189,  189,  189,  181,  112,  111,  185,  190,  190,  190,
      190,  190,  198,  110,  109,  185,  203,  108,  198,  185,

      189,  185,  191,  191,  191,  191,  191,  195,  195,  195,
      195,  195,  198,  203,  203,  191,  107,  106,  105,  102,
      195,  242,  101,  100,  191,  200,  243,  242,  191,  195,
      191,  203,  243,  195,  203,  195,  197,  197,  197,  197,
      197,  242,  200,  200,   99,  202,  243,  202,   98,  200,
      202,  202,  202,  202,  202,   97,   96,   95,  197,   94,
      200,   93,   92,  200,  205,  205,  205,  205,  205,  206,
      206,  206,  206,  206,  207,  207,  207,  207,  207,   91,
       87,   84,  206,   77,   68,   59,  205,   50,   45,   44,
       41,  206,   38,   35,   34,  206,  207,  206,  209,  209,

      209,  209,  209,  237,  237,  237,  237,  237,  238,  238,
      238,  238,  238,   31,   23,   15,  237,   12,   10,    7,
      209,    5,    3,    0,    0,  237,    0,    0,    0,  237,
      238,  237,  240,  240,  240,  240,  240,  241,  241,  241,
      241,  241,    0,    0,    0,  240,  244,  244,  244,  244,
      244,    0,    0,    0,  240,    0,    0,    0,  240,  241,
      240,  245,  245,  245,  245,  245,  264,  264,  264,  264,
      264,    0,    0,    0,  245,    0,    0,    0,    0,  264,
        0,    0,    0,  245,    0,    0,    0,  245,  264,  245,
        0,    0,  264,    0,  264,  266,  266,  266,  266,  266,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  266,  290,    0,
      290,  290,  290,  290,  290,  290,  291,    0,    0,  291,
      291,  291,  292,    0,  292,    0,  292,  292,  292,  292,
      293,  293,  293,  293,  293,  293,  293,  293,  294,    0,
      294,  294,  294,  294,  294,  294,  295,  295,  296,  296,
      296,  296,  296,  296,  296,  296,  298,  298,  298,  298,
      299,  299,  299,  299,  299,  299,  299,  299,  300,    0,
      300,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[89] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
// #include "genTAC.cpp"
#include <iostream>
#include <string>
#include "parser.tab.h"

using namespace std;
void yyerror (char *s);
extern "C" int yylex();


extern long long int line;
	
#line 766 "lex.yy.c"
#line 767 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 142 "lexer.l"


#line 987 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 290 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 782 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 144 "lexer.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 145 "lexer.l"
{ line++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 146 "lexer.l"
{ yylval.str=strdup(yytext); return(ABSTRACT); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 147 "lexer.l"
{yylval.str=strdup(yytext); return BOOLEAN;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 148 "lexer.l"
{yylval.str=strdup(yytext); return BREAK;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 149 "lexer.l"
{yylval.str=strdup(yytext); return BYTE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 150 "lexer.l"
{yylval.str=strdup(yytext); return CHAR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 151 "lexer.l"
{yylval.str=strdup(yytext); return CLASS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 152 "lexer.l"
{yylval.str=strdup(yytext); return CONST;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 153 "lexer.l"
{yylval.str=strdup(yytext); return CONTINUE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 154 "lexer.l"
{yylval.str=strdup(yytext); return DOUBLE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 155 "lexer.l"
{yylval.str=strdup(yytext); return ELSE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 156 "lexer.l"
{yylval.str=strdup(yytext); return FINAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 157 "lexer.l"
{yylval.str=strdup(yytext); return FLOAT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 158 "lexer.l"
{yylval.str=strdup(yytext); return FOR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 159 "lexer.l"
{yylval.str=strdup(yytext); return IF;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 160 "lexer.l"
{yylval.str=strdup(yytext); return INSTANCEOF;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 161 "lexer.l"
{yylval.str=strdup(yytext); return INT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 162 "lexer.l"
{yylval.str=strdup(yytext); return LONG;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 163 "lexer.l"
{yylval.str=strdup(yytext); return NEW;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 164 "lexer.l"
{yylval.str=strdup(yytext); return PACKAGE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 165 "lexer.l"
{yylval.str=strdup(yytext); return PRIVATE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 166 "lexer.l"
{yylval.str=strdup(yytext); return PUBLIC;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 167 "lexer.l"
{yylval.str=strdup(yytext); return RETURN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 168 "lexer.l"
{yylval.str=strdup(yytext); return SHORT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 169 "lexer.l"
{yylval.str=strdup(yytext); return STATIC;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 170 "lexer.l"
{yylval.str=strdup(yytext); return THIS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 171 "lexer.l"
{yylval.str=strdup(yytext); return VOID;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 172 "lexer.l"
{yylval.str=strdup(yytext); return WHILE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 175 "lexer.l"
{yylval.str=strdup(yytext); return '=';}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 176 "lexer.l"
{yylval.str=strdup(yytext); return '>';}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 177 "lexer.l"
{yylval.str=strdup(yytext); return '<';}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 178 "lexer.l"
{yylval.str=strdup(yytext); return '!';}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 179 "lexer.l"
{yylval.str=strdup(yytext); return '~';}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 180 "lexer.l"
{yylval.str=strdup(yytext); return '?';}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 181 "lexer.l"
{yylval.str=strdup(yytext); return ':';}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 182 "lexer.l"
{yylval.str=strdup(yytext); return PTR_OP;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 183 "lexer.l"
{yylval.str=strdup(yytext); return EQ_OP;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 184 "lexer.l"
{yylval.str=strdup(yytext); return GE_OP;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 185 "lexer.l"
{yylval.str=strdup(yytext); return LE_OP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 186 "lexer.l"
{yylval.str=strdup(yytext); return NE_OP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 187 "lexer.l"
{yylval.str=strdup(yytext); return INC_OP;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 188 "lexer.l"
{yylval.str=strdup(yytext); return DEC_OP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 189 "lexer.l"
{yylval.str=strdup(yytext); return OR_OP;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 190 "lexer.l"
{yylval.str=strdup(yytext); return AND_OP;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 191 "lexer.l"
{yylval.str=strdup(yytext); return '+';}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 192 "lexer.l"
{yylval.str=strdup(yytext); return '-';}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 193 "lexer.l"
{yylval.str=strdup(yytext); return '*';}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 194 "lexer.l"
{yylval.str=strdup(yytext); return '/';}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 195 "lexer.l"
{yylval.str=strdup(yytext); return '|';}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 196 "lexer.l"
{yylval.str=strdup(yytext); return '&';}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 197 "lexer.l"
{yylval.str=strdup(yytext); return '^';}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 198 "lexer.l"
{yylval.str=strdup(yytext); return '%';}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 199 "lexer.l"
{yylval.str=strdup(yytext); return RIGHT_OP;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 200 "lexer.l"
{yylval.str=strdup(yytext); return LEFT_OP;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 201 "lexer.l"
{yylval.str=strdup(yytext); return UNSIGNED_RIGHT_OP;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 202 "lexer.l"
{yylval.str=strdup(yytext); return ADD_ASSIGN;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 203 "lexer.l"
{yylval.str=strdup(yytext); return SUB_ASSIGN;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 204 "lexer.l"
{yylval.str=strdup(yytext); return MUL_ASSIGN;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 205 "lexer.l"
{yylval.str=strdup(yytext); return AND_ASSIGN;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 206 "lexer.l"
{yylval.str=strdup(yytext); return OR_ASSIGN;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 207 "lexer.l"
{yylval.str=strdup(yytext); return XOR_ASSIGN;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 208 "lexer.l"
{yylval.str=strdup(yytext); return DIV_ASSIGN;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 209 "lexer.l"
{yylval.str=strdup(yytext); return MOD_ASSIGN;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 210 "lexer.l"
{yylval.str=strdup(yytext); return RIGHT_ASSIGN;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 211 "lexer.l"
{yylval.str=strdup(yytext); return LEFT_ASSIGN;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 212 "lexer.l"
{yylval.str=strdup(yytext); return UNSIGNED_RIGHT_ASSIGN;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 215 "lexer.l"
{yylval.str=strdup(yytext); return '{';}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 216 "lexer.l"
{yylval.str=strdup(yytext); return '}';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 217 "lexer.l"
{yylval.str=strdup(yytext); return '[';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 218 "lexer.l"
{yylval.str=strdup(yytext); return ']';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 219 "lexer.l"
{yylval.str=strdup(yytext); return '(';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 220 "lexer.l"
{yylval.str=strdup(yytext); return ')';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 221 "lexer.l"
{yylval.str=strdup(yytext); return ',';}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 222 "lexer.l"
{yylval.str=strdup(yytext); return PROPORTION;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 223 "lexer.l"
{yylval.str=strdup(yytext); return '.';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 224 "lexer.l"
{yylval.str=strdup(yytext); return ';';}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 228 "lexer.l"
{ for(int i = 0; i<yyleng; ++i) if(yytext[i] == '\n') line++; /* comments, meant to be ignored */}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 230 "lexer.l"
{yylval.ival=atoi(yytext); return INTEGERLITERAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 231 "lexer.l"
{yylval.str=strdup(yytext); return FLOATINGPOINTLITERAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 232 "lexer.l"
{yylval.str=strdup(yytext); return TRUELITERAL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 233 "lexer.l"
{yylval.str=strdup(yytext); return FALSELITERAL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 234 "lexer.l"
{yylval.str=strdup(yytext); return NULLLITERAL;} 
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 235 "lexer.l"
{yylval.str=strdup(yytext); return CHARACTERLITERAL;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 237 "lexer.l"
{yylval.str=strdup(yytext); return STRINGLITERAL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 238 "lexer.l"
{yylval.str=strdup(yytext); return IDENTIFIER;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 239 "lexer.l"
{ cerr<<"Line:"<<line<<" :Error :: Illegal Character >>> "<<yytext<<"\n"; exit(-1); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 242 "lexer.l"
ECHO;
	YY_BREAK
#line 1496 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 290 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 290 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 289);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 242 "lexer.l"

int yywrap(){
    return 1;
}
